INSERT INTO ROLE_HIERARCHY
(ID,CHILD_NAME, PARENT_NAME)
VALUES ('1','ROLE_ADMIN','') ;

INSERT INTO ROLE_HIERARCHY
(ID,CHILD_NAME, PARENT_NAME)
VALUES ('2','ROLE_MANAGER', 'ROLE_ADMIN') ;

INSERT INTO ROLE_HIERARCHY
(ID,CHILD_NAME, PARENT_NAME)
VALUES ('3','ROLE_USER', 'ROLE_MANAGER') ;

(RESOURCE_ID,ORDER_NUM, RESOURCE_NAME, RESOURCE_TYPE)
VALUES ('1','1', '/admin/**', 'url') ;

INSERT INTO RESOURCES
(RESOURCE_ID,ORDER_NUM, RESOURCE_NAME, RESOURCE_TYPE)
VALUES ('2','2', '/mypage', 'url') ;

INSERT INTO RESOURCES
(RESOURCE_ID,ORDER_NUM, RESOURCE_NAME, RESOURCE_TYPE)
VALUES ('3','3', '/messages', 'url') ;

INSERT INTO RESOURCES
(RESOURCE_ID,ORDER_NUM, RESOURCE_NAME, RESOURCE_TYPE)
VALUES ('4','4', '/config**', 'url') ;

LECT * FROM ROLE;
ROLE_ID  	ROLE_DESC  	ROLE_NAME
(행 없음, 1 ms)

INSERT INTO ROLE
(ROLE_ID,ROLE_DESC, ROLE_NAME)
VALUES ('1','어드민', 'ROLE_ADMIN') ;

INSERT INTO ROLE
(ROLE_ID,ROLE_DESC, ROLE_NAME)
VALUES ('2','매니저', 'ROLE_MANAGER') ;

INSERT INTO ROLE
(ROLE_ID,ROLE_DESC, ROLE_NAME)
VALUES ('3','사용자', 'ROLE_USER') ;